<?php

/**
 * Example Shaka Streamer Configuration Output
 *
 * This file shows example configurations generated by the refactored CommandBuilder
 * when processing fluent API calls.
 */

// Example 1: Basic DASH output
$basicConfig = [
    'input_config' => [
        'inputs' => [
            [
                'input_type' => 'file',
                'name' => '/tmp/input.mp4',
                'media_type' => 'video'
            ],
            [
                'input_type' => 'file',
                'name' => '/tmp/input.mp4',
                'media_type' => 'audio'
            ]
        ]
    ],
    'pipeline_config' => [
        'streaming_mode' => 'vod',
        'manifest_format' => ['dash'],
        'dash_output' => '/output/manifest.mpd',
        'segment_size' => 10.0
    ]
];

// Example 2: Adaptive Bitrate with multiple video streams
$adaptiveBitrateConfig = [
    'input_config' => [
        'inputs' => [
            [
                'input_type' => 'file',
                'name' => '/tmp/input.mp4',
                'media_type' => 'video'
            ],
            [
                'input_type' => 'file',
                'name' => '/tmp/input.mp4',
                'media_type' => 'audio'
            ]
        ]
    ],
    'pipeline_config' => [
        'streaming_mode' => 'vod',
        'manifest_format' => ['dash', 'hls'],
        'dash_output' => '/output/dash/manifest.mpd',
        'hls_output' => '/output/hls/master.m3u8',
        'segment_size' => 6.0,
        'resolutions' => ['1080p', '720p', '480p'],
        'video_codecs' => ['h264', 'vp9'],
        'audio_codecs' => ['aac']
    ]
];

// Example 3: Encrypted DASH/HLS with raw key encryption
$encryptedConfig = [
    'input_config' => [
        'inputs' => [
            [
                'input_type' => 'file',
                'name' => '/tmp/input.mp4',
                'media_type' => 'video'
            ],
            [
                'input_type' => 'file',
                'name' => '/tmp/input.mp4',
                'media_type' => 'audio'
            ]
        ]
    ],
    'pipeline_config' => [
        'streaming_mode' => 'vod',
        'manifest_format' => ['dash', 'hls'],
        'dash_output' => '/output/manifest.mpd',
        'hls_output' => '/output/master.m3u8',
        'segment_size' => 10.0,
        'encryption' => [
            'enable' => true,
            'encryption_mode' => 'raw',
            'protection_systems' => ['Widevine', 'PlayReady', 'FairPlay'],
            'protection_scheme' => 'cenc',
            'keys' => [
                [
                    'key_id' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
                    'key' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
                    'label' => 'AUDIO'
                ],
                [
                    'key_id' => 'yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy',
                    'key' => 'yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy',
                    'label' => 'HD'
                ]
            ]
        ]
    ]
];

// Example 4: Live streaming configuration
$liveConfig = [
    'input_config' => [
        'inputs' => [
            [
                'input_type' => 'looped_file',
                'name' => '/tmp/input.mp4',
                'media_type' => 'video'
            ],
            [
                'input_type' => 'looped_file',
                'name' => '/tmp/input.mp4',
                'media_type' => 'audio'
            ]
        ]
    ],
    'pipeline_config' => [
        'streaming_mode' => 'live',
        'manifest_format' => ['dash', 'hls'],
        'dash_output' => '/output/manifest.mpd',
        'hls_output' => '/output/master.m3u8',
        'segment_size' => 4.0,
        'segment_per_file' => true,
        'availability_window' => 60,
        'presentation_delay' => 20,
        'update_period' => 3
    ]
];

// Example 5: Using withOption() for custom settings
$customConfig = [
    'input_config' => [
        'inputs' => [
            [
                'input_type' => 'file',
                'name' => '/tmp/input.mp4',
                'media_type' => 'video'
            ]
        ]
    ],
    'pipeline_config' => [
        'streaming_mode' => 'vod',
        'manifest_format' => ['dash'],
        'dash_output' => '/output/manifest.mpd',
        'segment_size' => 10.0,
        'low_latency_dash_mode' => true,
        'generate_iframe_playlist' => true
    ]
];

// Usage examples showing how CommandBuilder builds these configs:

/*
// Example: Basic DASH
$builder = CommandBuilder::make();
$builder
    ->addVideoStream('/tmp/input.mp4', 'video.mp4')
    ->addAudioStream('/tmp/input.mp4', 'audio.mp4')
    ->withMpdOutput('/output/manifest.mpd')
    ->withSegmentDuration(10);

$config = $builder->buildArray();
// Returns: $basicConfig

// Example: Adaptive Bitrate
$builder = CommandBuilder::make();
$builder
    ->addVideoStream('/tmp/input.mp4', 'video_1080p.mp4', ['bandwidth' => '5000000'])
    ->addVideoStream('/tmp/input.mp4', 'video_720p.mp4', ['bandwidth' => '3000000'])
    ->addVideoStream('/tmp/input.mp4', 'video_480p.mp4', ['bandwidth' => '1500000'])
    ->addAudioStream('/tmp/input.mp4', 'audio.mp4')
    ->withMpdOutput('/output/dash/manifest.mpd')
    ->withHlsMasterPlaylist('/output/hls/master.m3u8')
    ->withSegmentDuration(6);

$config = $builder->buildArray();
// Returns: $adaptiveBitrateConfig

// Example: With Encryption
$builder = CommandBuilder::make();
$builder
    ->addVideoStream('/tmp/input.mp4', 'video.mp4')
    ->addAudioStream('/tmp/input.mp4', 'audio.mp4')
    ->withMpdOutput('/output/manifest.mpd')
    ->withHlsMasterPlaylist('/output/master.m3u8')
    ->withEncryption([
        'enable' => true,
        'encryption_mode' => 'raw',
        'protection_systems' => ['Widevine', 'PlayReady', 'FairPlay'],
        'protection_scheme' => 'cenc',
        'keys' => [...]
    ]);

$config = $builder->buildArray();
// Returns: $encryptedConfig

// Example: Custom options
$builder = CommandBuilder::make();
$builder
    ->addVideoStream('/tmp/input.mp4', 'video.mp4')
    ->withMpdOutput('/output/manifest.mpd')
    ->withSegmentDuration(10)
    ->withOption('low_latency_dash_mode', true)
    ->withOption('generate_iframe_playlist', true);

$config = $builder->buildArray();
// Returns: $customConfig
*/
